name: Lint Check
run-name: ${{ github.actor }} ejecutando lint check
on: 
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    name: Ejecutar Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Instalar dependencias
        run: yarn install --frozen-lockfile
        
      - name: Ejecutar ESLint
        run: yarn lint