name: Lint Check
run-name: ${{ github.actor }} ejecutando lint check
on: 
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:

  # avoid_reduncy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cancelar builds previos
  #       uses: styfle/cancel-workflow-action@v0.10.0

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependencias correctamente
        run: yarn install --frozen-lockfile

  linter:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependencias
        run: yarn install --frozen-lockfile
      - name: Linter
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: [linter]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependencias
        run: yarn install --frozen-lockfile
      - name: correr Test
        run: yarn test
  #   steps:
  #     - name: Test
  #       run: yarn test
      # - uses: actions/checkout@v4
      
      # - name: Configurar Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
          
      # - name: Instalar dependencias
      #   run: yarn install --frozen-lockfile
        
      # - name: Ejecutar ESLint
      #   run: yarn lint

      # - name: Ejecutar Test
      #   run: yarn test